apiVersion: v2
name: harbor
description: A helm chart to deploy Harbor into Kubernetes
type: application
version: 1.0.0
appVersion: "0.27.6"
dependencies:
  - name: helm-charts
    alias: helm
    version: 1.17.1
    repository: oci://oci.tjth.co/ghcr/tjtharrison
  - name: harbor
    alias: harbor
    version: 1.17.1
    repository: https://helm.goharbor.io
  - name: k8s-backer-upper
    version: 1.3.0
    repository: oci://oci.tjth.co/ghcr/tjtharrison